[package]
name = "osrs-pathfinder-tile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[env]
GRID_SIZE_X = 100
GRID_SIZE_Y = 100

[dependencies]
